language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
script:
  - python setup.py -q install
  - python eveigb/tests/runtests.py eveigb.tests.tests:IGBHeadersTestCase